### ISSUE TITLE
Include URL on me.ehp246.aufrest.api.exception.RestFnException

### ISSUE THREAD

**Issue by ehp246** [ehp246/auf-rest#151]
`me.ehp246.aufrest.api.exception.RestFnException: java.net.ConnectException
at me.ehp246.aufrest.provider.httpclient.DefaultRestFnProvider$1.applyForResponse(DefaultRestFnProvider.java:154)
at me.ehp246.aufrest.core.rest.ByRestProxyFactory$1.lambda$invoke$1(ByRestProxyFactory.java:78)
at me.ehp246.aufrest.core.rest.FnOutcome.invoke(FnOutcome.java:28)
at me.ehp246.aufrest.core.rest.ByRestProxyFactory$1.invoke(ByRestProxyFactory.java:78)
at jdk.proxy3/jdk.proxy3.$Proxy229.post(Unknown Source)
at com.fadv.xtdforce.ssorunner.jms.screening.ssorunner.action.OnNewScreeningInviteStaged.executeCandidatePost(OnNewScreeningInviteStaged.java:138)
at com.fadv.xtdforce.ssorunner.jms.screening.ssorunner.action.OnNewScreeningInviteStaged.invoke(OnNewScreeningInviteStaged.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at me.ehp246.aufjms.api.inbound.BoundInvocable.invoke(BoundInvocable.java:30)
at me.ehp246.aufjms.core.inbound.DefaultInvocableDispatcher.lambda$dispatch$1(DefaultInvocableDispatcher.java:62)
at me.ehp246.aufjms.core.inbound.DefaultInvocableDispatcher.dispatch(DefaultInvocableDispatcher.java:111)
at me.ehp246.aufjms.core.inbound.DefaultInboundMessageListener.onMessage(DefaultInboundMessageListener.java:64)
at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736)
at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696)
at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:330)
at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:269)
at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237)
at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227)
at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException
at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:573)
at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
at me.ehp246.aufrest.provider.httpclient.DefaultRestFnProvider$1.applyForResponse(DefaultRestFnProvider.java:108)
... 23 more
Caused by: java.net.ConnectException
at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1055)
at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:198)
at java.net.http/jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56)
at java.net.http/jdk.internal.net.http.Http1Exchange.sendHeadersAsync(Http1Exchange.java:239)
at java.net.http/jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$9(Exchange.java:472)
at java.net.http/jdk.internal.net.http.Exchange.checkFor407(Exchange.java:404)
at java.net.http/jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$10(Exchange.java:476)
at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950)
at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2340)
at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:476)
at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:380)
at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Exchange.java:372)
at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:408)
at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:449)
at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950)
at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2340)
at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:439)
at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:341)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:157)
at java.base/java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2673)
at java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:294)
at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:654)
at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:552)
... 25 more
Caused by: java.nio.channels.UnresolvedAddressException
at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839)
at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:183)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:185)`

**Comment by ehp246** [comment]
To be released.
